export const channels = {
  windowMinimize: 'window:minimize',
  windowToggleMaximize: 'window:toggle-maximize',
  windowGetMaximized: 'window:get-maximized',
  windowMaximizedChanged: 'window:maximized-changed',
  windowClose: 'window:close',
  configGet: 'config:get',
  configSetMonitor: 'config:set-monitor',
  configSetAudioMode: 'config:set-audio-mode',
  configSetVolume: 'config:set-volume',
  configSetGlobalPaused: 'config:set-global-paused',
  configSetCloseToTray: 'config:set-close-to-tray',
  configSetAutoStart: 'config:set-auto-start',
  configChanged: 'config:changed',
  audioImport: 'audio:import',
  audioPreview: 'audio:preview',
  audioRestoreBuiltin: 'audio:restore-builtin',
  audioPlay: 'audio:play',
  audioResult: 'audio:result',
  hooksGetStatus: 'hooks:get-status',
  hooksInstall: 'hooks:install',
  hooksRepair: 'hooks:repair',
  runtimeGet: 'runtime:get',
  runtimeChanged: 'runtime:changed',
  logsOpenDirectory: 'logs:open-directory'
} as const
